# Generated by Django 5.0.1 on 2025-05-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstock',
            name='stock_status',
            field=models.CharField(choices=[('OK', 'OK'), ('CRITICAL', 'Critical'), ('OUT_OF_STOCK', 'Out of Stock')], default='OK', max_length=20),
        ),
        migrations.AddField(
            model_name='currentstock',
            name='threshold',
            field=models.IntegerField(default=5),
        ),
    ]
